# Generated by Django 4.0.2 on 2022-05-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="isVerified",
            field=models.BooleanField(default=False),
        ),
    ]
