# Generated by Django 4.0.2 on 2022-05-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_profile_isverified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="isVerified",
            field=models.BooleanField(default=True),
        ),
    ]
