language: python

python:
  - 3.8

env:
  - SECRET_KEY='django-secure-#cqhtip#_$ek$ail5(e#=_df_)279o#f)h$md_p38n*ukq1w^_'

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coverage
  - pip install coveralls

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - python -m black . --check
  - python -m flake8 --max-line-length=150
  - python -m coverage run --source='.' manage.py test

after_success:
  - coveralls
