language: python

python:
  - 3.9

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coverage
  - pip install coveralls

before_script:
  - python manage.py migrate

script:
  - python -m black . --check
  - black .
  - flake8 .
  - python -m coverage run --source='.' manage.py test

after_script:
  - coveralls
