language: python

python:
  - 3.9

env:
  - EMAIL_HOST=smtp.gmail.com
  - EMAIL_HOST_USER=houseme2022@gmail.com
  - EMAIL_HOST_PASSWORD=psadsihpvakyumvt
  - AWS_ACCESS=ABC
  - AWS_SECRET=XYZ


install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coverage
  - pip install coveralls

before_script:
  - python manage.py migrate

script:
  - black .
  - python -m black . --check
  - flake8 .
  - python -m coverage run --source=. manage.py test

after_script:
  - coveralls
