language: python

python:
  - 3.9

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coverage
  - pip install coveralls

env:
  - EMAIL_HOST=smtp.gmail.com EMAIL_HOST_USER=houseme2022@gmail.com EMAIL_HOST_PASSWORD=psadsihpvakyumvt AWS_ACCESS=ABC AWS_SECRET=XYZ GOOGLE_API_KEY=ABC DEBUG= True

before_script:
  - python manage.py migrate

script:
  - black .
  - python -m black . --check
  - flake8 .
  - python -m coverage run --source=. manage.py test
  - python -m coverage report -m

after_script:
  - coveralls
