# Generated by Django 3.0.3 on 2022-02-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0002_listing_borough'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='area',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='listing',
            name='laundry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='map_url',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='listing',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathroom',
            field=models.IntegerField(default=-1),
        ),
    ]
