# Generated by Django 3.0.3 on 2022-02-27 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=-1, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=-1, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=-1, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address1', models.CharField(default=-1, max_length=100)),
                ('address2', models.CharField(default=-1, max_length=120)),
                ('zipcode', models.CharField(default=-1, max_length=8)),
                ('latitude', models.CharField(default='', max_length=300)),
                ('longitude', models.CharField(default='', max_length=300)),
                ('rent', models.IntegerField(default=-1)),
                ('description', models.CharField(default='-', max_length=300)),
                ('bedrooms', models.IntegerField(default=-1)),
                ('furnished', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('heating', models.BooleanField(default=False)),
                ('ratings', models.FloatField(default=-1)),
                ('bathroom', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('photo_url', models.CharField(default=-1, max_length=300)),
                ('matterport_link', models.CharField(default=-1, max_length=300)),
                ('city', models.ForeignKey(db_column='city_name', default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='Property.City')),
                ('state', models.ForeignKey(db_column='state_name', default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='class_state', to='Property.State')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(db_column='state_id', default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='Property.State'),
        ),
    ]
