<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-03-08 03:34
=======
# Generated by Django 4.0.2 on 2022-03-08 02:46
>>>>>>> 89590840858b288d90bc1aba1fd6d8a10b069f17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userofapp',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
