# Generated by Django 3.0.3 on 2022-02-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='borough',
            field=models.CharField(default=-1, max_length=120),
        ),
    ]
