# Generated by Django 4.0.1 on 2022-04-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
