# Generated by Django 4.0.1 on 2022-03-25 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo_url',
        ),
    ]
