# Generated by Django 4.0.2 on 2022-03-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='map_url',
        ),
        migrations.AlterField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='address1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address_1'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='address2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Address_2'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.FloatField(default=0, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(default=1, verbose_name='Bathrooms'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(default=1, verbose_name='Bedrooms'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='borough',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Borough'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='calendly_link',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Calendly_Link'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='elevator',
            field=models.BooleanField(default=False, verbose_name='Elevator'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='furnished',
            field=models.BooleanField(default=False, verbose_name='Furnished'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='heating',
            field=models.BooleanField(default=False, verbose_name='Heating'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='laundry',
            field=models.BooleanField(default=False, verbose_name='Laundry'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='matterport_link',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Matterport_Link'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='Parking'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Photo_Url'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='ratings',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rent',
            field=models.IntegerField(default=1, verbose_name='Rent'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='zipcode',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='userofapp',
            name='zip',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
