# Generated by Django 4.0.4 on 2022-05-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Property", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="latitude",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Latitude"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="longitude",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Longitude"
            ),
        ),
    ]
