# Generated by Django 4.0.1 on 2022-04-13 22:27

import Property.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=Property.models.get_image_filename, verbose_name='Image'),
        ),
    ]
