# Generated by Django 4.0.2 on 2022-04-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0002_listing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
