# Generated by Django 4.0.1 on 2022-03-25 02:46

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0002_remove_listing_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo_url',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
