# Generated by Django 4.0.1 on 2022-04-10 22:09

import Property.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0003_remove_listing_photo_url_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=Property.models.get_image_filename, verbose_name='Image'),
        ),
    ]
