# Generated by Django 4.0.1 on 2022-03-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0003_listing_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_url',
            field=models.FileField(upload_to='media/'),
        ),
    ]
