# Generated by Django 4.0.1 on 2022-03-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0004_alter_listing_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_url',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
