# Generated by Django 4.0.1 on 2022-03-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0002_alter_userofapp_first_name'),
        ('Property', '0004_auto_20220319_0224'),
    ]

    operations = [
    ]
