# Generated by Django 4.0.1 on 2022-03-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0005_alter_listing_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_url',
            field=models.ImageField(blank=True, default='images/house1.png', null=True, upload_to='media/'),
        ),
    ]
